name: Build latest image

on:
  push:
    branches:
      - master

env:
  IMAGE: hello-world

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Docker Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag build-image

      - name: Push Docker image
        run: |
          docker tag build-image docker.pkg.github.com/${{ github.repository }}/$IMAGE:latest
          docker push docker.pkg.github.com/${{ github.repository }}/$IMAGE:latest
