name: Build latest image

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Docker Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/${{ github.repository }}/hello-world:release-${{ github.ref }}

      - name: Push Docker image
        run: docker push docker.pkg.github.com/${{ github.repository }}/hello-world:release-${{ github.ref }}
