name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types: [opened, synchronize, reopened]

env:
  IMAGE_NAME: hello-world

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: build
        run: docker-compose -f docker-compose.test.yml build

      - name: test
        run: docker-compose -f docker-compose.test.yml run sut

  push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name }} == 'push'

    steps:
      - uses: actions/checkout@v1

      - name: Docker Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag build-image

      - name: Push Docker image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag build-image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
