name: Publish Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Docker Login
        run: docker login docker.pkg.github.com -u ${OWNER} -p ${{secrets.GPR_AUTH_TOKEN}}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/${OWNER}/docker-actions-sandbox/hello-world:$(date +%s)
