name: Publish Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Docker Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u josh --password-stdin

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/josh/docker-actions-sandbox/hello-world:${{ github.sha }}

      - name: Push Docker image
        run: docker push docker.pkg.github.com/josh/docker-actions-sandbox/hello-world:${{ github.sha }}
