name: Publish Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Docker Login
        run: docker login docker.pkg.github.com -u josh -p "${{ secrets.GITHUB_TOKEN }}"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/josh/docker-actions-sandbox/hello-world:$(date +%s)
